save-arenas-on-edit: false
broadcast-on-hit: false
max-dodgeballs-held: 5
lives-standard:
    starting: 3
    max: 5
    lost-on-death: 1
    gained-on-hit: 0
timers:
    starting: 60
    game: 300
    arena-menu-update-interval: 15
global-lobby:
    world: world
    x: 100
    y: 66
    z: 100
    yaw: 0
    pitch: 0
arena-menus:
    Ice Rink:
        item: ice
        arenas:
            - IceRink_1
            - IceRink_2
            - IceRink_3
            - IceRink_4
            - IceRink_5
            - IceRink_6
    Garden:
        item: sapling
        arenas:
            - Garden_1
            - Garden_2
            - Garden_3
            - Garden_4
            - Garden_5
            - Garden_6
    Nether Madness:
        item: netherrack
        arenas:
            - NetherMadness1
            - NetherMadness2
            - NetherMadness3
            - NetherMadness4
            - NetherMadness5
            - NetherMadness6
    Gym:
        item: brick
        arenas:
            - Gym_1
            - Gym_2
            - Gym_3
            - Gym_4
            - Gym_5
            - Gym_6
    Courtyard:
        item: brick
        arenas:
            - Courtyard_1
            - Courtyard_2
            - Courtyard_3
            - Courtyard_4
            - Courtyard_5
            - Courtyard_6            
